[font]
size = 16 # normal: 16 broadcast: 22

normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[env]
TERM = "xterm-256color"

[colors.cursor]
text = "#ffffff"
cursor = "#d25858" # red

[window]
title="sh-0"
dynamic_title = false
padding = { x = 16, y = 8 }
dynamic_padding = true
decorations = "None"
blur = false
opacity = 0.85 # default: 0.85
dimensions = { columns = 60, lines = 10 } # act as gateway for terminal window manager.

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
#  { key = "V", mods = "Control", action = "Paste" },
#  { key = "C", mods = "Control|Shift", action = "Copy" },
   { key = "Space", mods = "Control", chars = "\u0000" },
]

# @NOTE: run `win.alacritty.config.deploy` after editing to sync it to the Windows side.
