gui:
  border: "single"
  showBottomLine: false
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - '#969896'
      # - '#424242'
    selectedLineBgColor:
      - '#4d4d4d'
