return {}

-- return {
--   "folke/zen-mode.nvim",
--   config = function()
--     require("zen-mode").setup({
--       window = {
--         backdrop = 0,
--         width = 100,
--         height = 1,
--       },
--       plugins = {
--         enabled = true,
--         ruler = true,
--       },
--     options = {
--         -- signcolumn = "no", -- disable signcolumn
--         -- number = false, -- disable number column
--         -- relativenumber = false, -- disable relative numbers
--         -- cursorline = false, -- disable cursorline
--         -- cursorcolumn = false, -- disable cursor column
--         -- foldcolumn = "0", -- disable fold column
--         -- list = false, -- disable whitespace characters
--         list = true, -- enable whitespace characters
--         signcolumn = "yes", -- enable signcolumn
--       },
--     })
--
--     vim.keymap.set("n", "<leader>z", ":ZenMode<CR>", {})
--   end,
-- }
